import '@/styles/globals.css';
import "@/styles/coresBB.css";
import "@/styles/TinyMCE.css";
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { ChakraProvider, Box } from "@chakra-ui/react";
import Footer from "@/components/Footer";
import NavBar from "@/components/Navbar";
import NavBarBlank from '@/components/NavBarBlank';



export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Blog-App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ChakraProvider>
        <Box height={"100vh"} display={"flex"} flexDirection={"column"} justifyContent={"space-between"}>
          <Box>
            <NavBar />
            <NavBarBlank />
          </Box>
          <Component  {...pageProps} />
          <Footer />
        </Box>
      </ChakraProvider >
    </>
  )

}
